#include <donut/cli.hpp>
#include <donut/exec.hpp>
#include <donut/net.hpp>
#include <donut/version.h>

#include <unistd.h>

#include <cerrno>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <span>
#include <string>
#include <string_view>
#include <vector>

namespace {

constexpr std::string_view kProgram = "donut-changeip";
constexpr std::string_view kToolVersion = CHANGEIP_VERSION;
constexpr std::string_view kSummary =
    "Change the IPv4 address of a network interface, or switch it between static and DHCP, and optionally its default gateway and DNS servers.";
constexpr std::string_view kUsageLine =
    "donut-changeip -i <iface> [--address <ip[/mask]> | --mode dhcp] [options]";
constexpr std::string_view kDefaultDns = "1.1.1.1,8.8.8.8";
constexpr std::string_view kResolvConf = "/etc/resolv.conf";
constexpr std::string_view kResolvBackup = "/etc/resolv.conf.donut.bak";
constexpr std::string_view kNetplanDir = "/etc/netplan";
// One file per interface, so configuring a second interface never drops the
// settings of the first. The 90- prefix keeps it after distro defaults.
constexpr std::string_view kNetplanFilePrefix = "/etc/netplan/90-donut-changeip-";

const donut::cli::Option kOptions[] = {
    {"interface", 'i', "<iface>", "network interface to configure", true},
    {"address", 'a', "<ip[/mask]>",
     "static IPv4 address with prefix length, e.g. 192.168.1.10/24 "
     "(default /24); implies --mode static", false},
    {"mode", 'm', "<dhcp|static>",
     "configuration mode for the interface (default: static when --address "
     "is given)", false},
    {"gateway", 'g', "<ip>", "default gateway IPv4 address (static only)", false},
    {"dns", 'd', "<servers>",
     "comma-separated DNS servers (default: 1.1.1.1,8.8.8.8)", false},
    {"no-dns", 0, "", "leave DNS configuration untouched", false},
    {"dry-run", 'n', "", "show what would be done without applying anything", false},
    {"help", 'h', "", "show this help and exit", false},
    {"version", 'v', "", "show version information and exit", false},
};

std::string to_lower(std::string s) {
    for (char& c : s) {
        if (c >= 'A' && c <= 'Z') c = static_cast<char>(c - 'A' + 'a');
    }
    return s;
}

bool run_command(const std::vector<std::string>& cmd, bool dry_run) {
    if (dry_run) {
        std::cout << "would run:";
        for (const auto& arg : cmd) std::cout << ' ' << arg;
        std::cout << '\n';
        return true;
    }
    const int status = donut::exec::run(cmd);
    if (status != 0) {
        std::cerr << kProgram << ": command failed (status " << status << "):";
        for (const auto& arg : cmd) std::cerr << ' ' << arg;
        std::cerr << '\n';
        return false;
    }
    return true;
}

// True if netplan is usable on this system. Checked quietly, so that it also
// works in --dry-run.
bool netplan_available() {
    namespace fs = std::filesystem;
    std::error_code ec;
    if (!fs::exists(fs::path(kNetplanDir), ec)) return false;
    return donut::exec::run(std::vector<std::string>{
               "sh", "-c", "command -v netplan >/dev/null 2>&1"}) == 0;
}

std::string build_netplan_yaml(const std::string& iface, bool dhcp,
                               const std::string& cidr, const std::string& gateway,
                               const std::vector<std::string>& dns) {
    std::string out;
    out += "# Generated by donut-changeip; changes to this file are overwritten.\n";
    out += "network:\n";
    out += "  version: 2\n";
    out += "  ethernets:\n";
    out += "    " + iface + ":\n";
    out += dhcp ? "      dhcp4: true\n" : "      dhcp4: false\n";
    if (!dhcp) {
        out += "      addresses:\n";
        out += "        - " + cidr + "\n";
        if (!gateway.empty()) {
            out += "      routes:\n";
            out += "        - to: default\n";
            out += "          via: " + gateway + "\n";
        }
    }
    if (!dns.empty()) {
        out += "      nameservers:\n";
        out += "        addresses:\n";
        for (const auto& server : dns) {
            out += "          - " + server + "\n";
        }
    }
    return out;
}

// Writes the netplan file with owner-only permissions; netplan refuses or
// warns about world-writable or world-readable configuration.
bool write_netplan_file(const std::string& path_str, const std::string& content) {
    namespace fs = std::filesystem;
    const fs::path path(path_str);

    std::ofstream out(path, std::ios::trunc);
    if (!out) {
        std::cerr << kProgram << ": cannot open " << path_str << ": "
                  << std::strerror(errno) << '\n';
        return false;
    }
    out << content;
    out.close();
    if (!out) {
        std::cerr << kProgram << ": error writing " << path_str << ": "
                  << std::strerror(errno) << '\n';
        return false;
    }

    std::error_code ec;
    fs::permissions(path, fs::perms::owner_read | fs::perms::owner_write,
                    fs::perm_options::replace, ec);
    return true;
}

bool write_dns(const std::vector<std::string>& servers, bool dry_run) {
    if (dry_run) {
        std::cout << "would write " << kResolvConf << ":\n";
        for (const auto& server : servers) {
            std::cout << "nameserver " << server << '\n';
        }
        return true;
    }

    namespace fs = std::filesystem;
    const fs::path path(kResolvConf);
    const fs::path backup(kResolvBackup);
    std::error_code ec;

    // Back up the current file. If resolv.conf is a symlink (systemd-resolved
    // stub), copy_file() follows it and saves the original contents.
    if (fs::exists(fs::symlink_status(path, ec)) && !fs::exists(backup, ec)) {
        fs::copy_file(path, backup, ec);
    }
    fs::remove(path, ec);

    std::ofstream out(path, std::ios::trunc);
    if (!out) {
        std::cerr << kProgram << ": cannot open " << kResolvConf << ": "
                  << std::strerror(errno) << '\n';
        return false;
    }
    out << "# generated by donut " << kProgram << '\n';
    for (const auto& server : servers) {
        out << "nameserver " << server << '\n';
    }
    out.close();
    if (!out) {
        std::cerr << kProgram << ": error writing " << kResolvConf << ": "
                  << std::strerror(errno) << '\n';
        return false;
    }
    return true;
}

}  // namespace

int main(int argc, char* argv[]) {
    donut::cli::Arguments args;
    std::string error;
    if (!donut::cli::parse(argc, argv, kOptions, args, error)) {
        std::cerr << kProgram << ": " << error << "\ntry '" << kProgram
                  << " --help' for more information\n";
        return 2;
    }
    if (args.has("help")) {
        donut::cli::print_usage(kProgram, kToolVersion, kSummary, kUsageLine, kOptions);
        return 0;
    }
    if (args.has("version")) {
        donut::cli::print_version(kProgram, kToolVersion);
        return 0;
    }
    if (!donut::cli::check_required(kOptions, args, error)) {
        std::cerr << kProgram << ": " << error << "\ntry '" << kProgram
                  << " --help' for more information\n";
        return 2;
    }

    const std::string iface = args.value("interface");
    const std::string address_arg = args.value("address");
    const std::string gateway = args.value("gateway");
    const std::string mode_arg = args.value("mode");
    const bool no_dns = args.has("no-dns");
    const bool dry_run = args.has("dry-run");

    if (!donut::net::valid_interface(iface)) {
        std::cerr << kProgram << ": invalid interface name '" << iface << "'\n";
        return 2;
    }

    // Resolve the configuration mode. --address implies static, so the mode
    // only has to be given for DHCP (or to be explicit about static).
    bool dhcp = false;
    if (!mode_arg.empty()) {
        const std::string mode = to_lower(mode_arg);
        if (mode != "dhcp" && mode != "static") {
            std::cerr << kProgram << ": invalid mode '" << mode_arg
                      << "', expected dhcp or static\n";
            return 2;
        }
        dhcp = mode == "dhcp";
    } else if (args.has("address")) {
        dhcp = false;
    } else {
        std::cerr << kProgram << ": either --address or --mode dhcp is required\n";
        return 2;
    }
    if (dhcp && args.has("address")) {
        std::cerr << kProgram << ": --address cannot be combined with --mode dhcp\n";
        return 2;
    }
    if (dhcp && args.has("gateway")) {
        std::cerr << kProgram << ": --gateway cannot be combined with --mode dhcp\n";
        return 2;
    }

    std::string cidr;
    if (!dhcp) {
        if (!args.has("address")) {
            std::cerr << kProgram << ": static mode requires --address\n";
            return 2;
        }
        std::string ip;
        int prefix = -1;
        if (!donut::net::parse_cidr(address_arg, ip, prefix)) {
            std::cerr << kProgram << ": invalid address '" << address_arg
                      << "', expected <ipv4>[/<prefix>]\n";
            return 2;
        }
        if (address_arg.find('/') == std::string::npos) {
            std::cout << kProgram << ": no prefix given, using /24\n";
        }
        cidr = ip + '/' + std::to_string(prefix);

        if (args.has("gateway") && !donut::net::is_ipv4(gateway)) {
            std::cerr << kProgram << ": invalid gateway '" << gateway << "'\n";
            return 2;
        }
    }

    std::vector<std::string> dns;
    if (!no_dns) {
        std::string dns_arg;
        if (args.has("dns")) {
            dns_arg = args.value("dns");
        } else if (!dhcp) {
            dns_arg = kDefaultDns;
        }
        if (!dns_arg.empty()) {
            if (!donut::net::split_csv(dns_arg, dns)) {
                std::cerr << kProgram << ": invalid DNS server list '" << dns_arg << "'\n";
                return 2;
            }
            for (const auto& server : dns) {
                if (!donut::net::is_ipv4(server)) {
                    std::cerr << kProgram << ": invalid DNS server '" << server << "'\n";
                    return 2;
                }
            }
        }
    }

    if (!dry_run && geteuid() != 0) {
        std::cerr << kProgram << ": must be run as root\n";
        return 1;
    }

    if (netplan_available()) {
        // Netplan mode: write our own file under /etc/netplan and let netplan
        // apply it. The 90- prefix makes it sort after distro defaults (e.g.
        // 50-cloud-init.yaml), so the donut settings win for this interface;
        // other netplan files are left alone. DNS is part of the netplan
        // configuration, so /etc/resolv.conf is not edited here.
        std::cout << kProgram << ": using netplan, writing " << kNetplanDir << '/'
                  << "90-donut-changeip-" << iface << ".yaml\n";
        const std::string netplan_file =
            std::string(kNetplanFilePrefix) + iface + ".yaml";
        const std::string yaml = build_netplan_yaml(iface, dhcp, cidr, gateway, dns);
        if (dry_run) {
            std::cout << "would write " << netplan_file << ":\n" << yaml;
        } else if (!write_netplan_file(netplan_file, yaml)) {
            return 1;
        }
        if (!run_command({"netplan", "apply"}, dry_run)) return 1;
    } else {
        // Fallback without netplan: configure the running system directly.
        // DHCP mode uses dhclient, which replaces the address (and usually
        // the DNS servers) itself, so resolv.conf is only written when
        // explicit DNS servers were resolved above.
        std::cout << kProgram << ": netplan not found, configuring directly\n";
        if (!run_command({"ip", "link", "set", "dev", iface, "up"}, dry_run)) return 1;
        if (dhcp) {
            if (!run_command({"ip", "-4", "addr", "flush", "dev", iface}, dry_run)) {
                return 1;
            }
            if (!run_command({"dhclient", iface}, dry_run)) return 1;
        } else {
            std::cout << kProgram << ": configuring " << iface << " with " << cidr << '\n';
            if (!run_command({"ip", "-4", "addr", "flush", "dev", iface}, dry_run)) {
                return 1;
            }
            if (!run_command({"ip", "addr", "add", cidr, "dev", iface}, dry_run)) {
                return 1;
            }
            if (args.has("gateway")) {
                if (!run_command({"ip", "route", "replace", "default", "via", gateway,
                                  "dev", iface},
                                 dry_run)) {
                    return 1;
                }
            }
        }
        if (!dns.empty()) {
            std::cout << kProgram << ": setting DNS servers:";
            for (const auto& server : dns) std::cout << ' ' << server;
            std::cout << '\n';
            if (!write_dns(dns, dry_run)) return 1;
        }
    }

    std::cout << kProgram << ": done\n";
    return 0;
}
